stages:
    - builds
    - tests
    - fmt
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - rustup update
    
build-rust-stable:
  stage: builds
  tags:
    - redshift-rs-stable
  script:
    - cargo build
    
build-rust-beta:
  stage: builds
  tags:
    - redshift-rs-beta
  script:
    - cargo build
    
build-rust-nightly:
  stage: builds
  tags:
    - redshift-rs-nightly
  script:
    - cargo build
    
test-rust-stable:
  stage: tests
  tags:
    - redshift-rs-stable
  script:
    - cargo test
    
test-rust-beta:
  stage: tests
  tags:
    - redshift-rs-beta
  script:
    - cargo test
  when: manual
  only:
    - master
    
test-rust-nightly:
  stage: tests
  tags:
    - redshift-rs-nightly
  script:
    - cargo test
  when: manual
  only:
    - master
    
fmt:
  stage: fmt
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo install --force rustfmt-nightly
  script:
    - cargo fmt -- --write-mode=diff
  when: manual
  only:
    - master
