stages:
    - build_and_tests
    - fmt
    - clippy
    - publish
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"

.rust_stable_env: &rust_stable_env
  tags:
    - redshift-rs-stable
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"

.rust_beta_env: &rust_beta_env
  tags:
    - redshift-rs-beta
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - rustup update

.rust_nightly_env: &rust_nightly_env
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    
build_and_tests:stable:
  <<: *rust_stable_env
  stage: build_and_tests
  tags:
    - redshift-rs-stable
  script: 
    - cargo build --features strict
    - cargo test --all
    
build_and_tests:beta:
  <<: *rust_beta_env
  stage: build_and_tests
  script:
    - cargo build --features strict
    - cargo test --all
  when: manual
  allow_failure: true
    
build_and_tests:nightly:
  <<: *rust_nightly_env
  stage: build_and_tests
  script:
    - cargo build --features strict
    - cargo test --all
  when: manual
  allow_failure: true
  
fmt:
  <<: *rust_nightly_env
  stage: fmt
  before_script:
    - cargo install --force rustfmt-nightly
  script:
    - cargo fmt -- --check
  allow_failure: true

clippy:
  <<: *rust_nightly_env
  stage: clippy
  before_script:
    - cargo install --force clippy --verbose
  script:
    - cargo clippy --all -- -D warnings --verbose
  allow_failure: true  

publish:crate:
  <<: *rust_stable_env
  stage: publish
  script:
    - IFS='/' read -r first a <<< "$CI_COMMIT_TAG"
    - cd $first
    - cargo login $DUNITER_CRATES_TOKEN
    - cargo publish
  only:
    - tags
  allow_failure: false
  when: manual

release:
  <<: *rust_stable_env
  stage: publish
  script:
    - cargo build --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/durs
  when: manual

pages:
  <<: *rust_stable_env
  stage: publish
  script:
    - cargo doc
    - mv target/doc public
    - ls public
  artifacts:
    untracked: true
    paths:
      - public
  allow_failure: true
  when: manual