stages:
    - builds
    - tests
    - fmt
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    
build:stable:
  stage: builds
  tags:
    - redshift-rs-stable
  script:
    - cargo build
    
tests:stable:
  stage: tests
  tags:
    - redshift-rs-stable
  script:
    - cargo test
    
build_and_tests:beta:
  stage: tests
  tags:
    - redshift-rs-beta
  script:
    - rustup update
    - cargo test
  when: manual
  allow_failure: true
    
build_and_tests:nightly:
  stage: tests
  tags:
    - redshift-rs-nightly
  script:
    - rustup update
    - cargo test
  when: manual
  allow_failure: true
  
fmt:
  stage: fmt
  image: scorpil/rust:nightly-onbuild
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo install --force rustfmt-nightly
  script:
    - cargo fmt -- --write-mode=diff
  allow_failure: true

