stages:
    - builds
    - tests
    - fmt
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    
builds:
  stage: builds
  tags:
    - redshift-rs
  script:
    - cargo build
    
tests:
  stage: tests
  tags:
    - redshift-rs
  script:
    - cargo test
    
fmt:
  stage: fmt
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo +nightly install --force rustfmt-nightly
  script:
    - cargo +nightly fmt -- --write-mode=diff
