stages:
    - builds
    - tests
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    
builds:
  stage: builds
  tags:
    - redshift-rs
  script:
    - cargo build
    
tests:
  stage: tests
  tags:
    - redshift-rs
  script:
    - cargo test
