stages:
    - build_and_tests
    - clippy
    - fmt
    - publish
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    
build_and_tests:stable:
  stage: build_and_tests
  tags:
    - redshift-rs-stable
  script: 
    - cargo build --features strict
    - cargo test --all
    
build_and_tests:beta:
  stage: build_and_tests
  tags:
    - redshift-rs-beta
  script:
    - rustup update
    - cargo build --features strict
    - cargo test --all
  when: manual
  allow_failure: true
    
build_and_tests:nightly:
  stage: build_and_tests
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  script:
    - cargo build --features strict
    - cargo test --all
  when: manual
  allow_failure: true
  
clippy:
  stage: clippy
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo install --force clippy --verbose
  script:
    - cargo clippy --all -- -D warnings --verbose
  allow_failure: true  
  
fmt:
  stage: fmt
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo install --force rustfmt-nightly
  script:
    - cargo fmt -- --write-mode=diff
  allow_failure: true

publish:crate:
  stage: publish
  tags:
    - redshift-rs-stable
  script:
    - IFS='/' read -r first a <<< "$CI_COMMIT_TAG"
    - cd $first
    - cargo login $DUNITER_CRATES_TOKEN
    - cargo publish
  only:
    - tags
  allow_failure: false
  when: manual