[package]
name = "durs"
version = "0.1.0"
authors = ["librelois <elois@duniter.org>","nanocryk <nanocryk@duniter.org>"]
description = "DUniter-RS (durs) is a new implementation of Duniter protocol and software in Rust, a safe, concurrent, practical language"
license = "AGPL-3.0"

[dependencies]
duniter-conf = { path = "./conf" }
duniter-core = { path = "./core" }
duniter-tui = { path = "./tui", optional = true }
duniter-ws2p = { path = "./ws2p" }

[features]
default = ["tui","ssl"]
ssl = ["duniter-ws2p/ssl"]
tui = ["duniter-tui"]
# Treat warnings as a build error.
strict = []

[workspace]
members = [
    "blockchain",
    "conf",
    "core",
    "crypto",
    "dal",
    "documents",
    "message",
    "module",
    "network",
    "tui",
    "wotb",
    "ws2p"
]
