[package]
name = "durs"
version = "0.1.0"
authors = ["librelois <elois@duniter.org>","nanocryk <nanocryk@duniter.org>"]
description = "DUniter-RS (durs) is a new implementation of Duniter protocol and software in Rust, a safe, concurrent, practical language"
license = "AGPL-3.0"

[dependencies]
clap = "2.31.2"
duniter-core = { path = "./core" }
duniter-tui = { path = "./tui" }
duniter-ws2p = { path = "./ws2p" }
lazy_static = "1.0.0"
serde_json = "1.0.9"
websocket = "0.20.2"

[workspace]
members = [
    "blockchain",
    "conf",
    "core",
    "crypto",
    "dal",
    "documents",
    "message",
    "module",
    "network",
    "tui",
    "wotb",
    "ws2p",
]
